<?php

namespace AppBundle\Repository;

/**
 * PlayedGameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayedGameRepository extends \Doctrine\ORM\EntityRepository
{

    public function playerWinTotal($playerID)
    {
		$em = $this->getEntityManager();

		$query = $em->createQuery(
			'SELECT COUNT (pg)
			FROM AppBundle:PlayedGame pg
			WHERE pg.winningPlayerID = :playerID'
		)->setParameter(':playerID', $playerID);

		return $query->getSingleScalarResult();
    }

}
